services:
  analizador-cv:
    build: .
    container_name: cv_analyzer_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: always